Adding new targets so it can be more easily embedded without cocoa pods
launchdarkly/ios-eventsource pull request #25
Opened 2019-02-07 15:57 UTC by rafaelsimonmaia

## What
No code changes, only added a few targets to make it easier to integrate without CocoaPods.

## Test 
Compile each Target. They should all succeed.

2019-02-08 20:11 UTC, markpokornycos requested changes

2019-02-08 20:11 UTC, markpokornycos commented on LDEventSource.xcodeproj/project.pbxproj
> +				78D92EB1220BB50400585033 /* DarklyEventSource-WatchOS-Info.plist */,
These 3 info.plist files are absolute referenced to files on your machine. When I open the project they are red. The files are in my file system. All 3 files are copies of the Info.plist in the LDEventSource directory.

I recommend deleting these 3 plists, and instead referencing the original in the new targets by changing the Info.plist reference in the Packaging Build Setting to `$(SRCROOT)/LDEventSource/Info.plist`

2019-02-08 20:11 UTC, markpokornycos commented on LDEventSource.xcodeproj/project.pbxproj
> +		78D92E9C220BB50400585033 /* DarklyEventSource-WatchOS */ = {
#picky name this to `DarklyEventSource-watchOS`

2019-02-08 20:11 UTC, markpokornycos commented on LDEventSource.xcodeproj/project.pbxproj
> +		78D92EB2220BB51700585033 /* DarklyEventSource-tvOs */ = {
#picky name this to `DarklyEventSource-tvOS`

2019-02-08 20:11 UTC, markpokornycos commented on LDEventSource.xcodeproj/project.pbxproj
> +		78D92EC8220BB51F00585033 /* DarklyEventSource-MacOs */ = {
#picky name this `DarklyEventSource-macOS`

2019-02-11 22:02 UTC, markpokornycos commented
Add schemes for DarklyEventSource_tvOS & _macOS

2019-02-12 19:33 UTC, markpokornycos approved these changes

2019-02-12 19:35 UTC, rafaelsimonmaia commented
Looks good now. Thanks Mark.

2019-02-12 19:54 UTC, arun251 approved these changes
👍

2019-02-12 20:13 UTC, merged